### ISSUE TITLE
Is there any documentation explaining the principle?

### ISSUE THREAD

**Issue by liuxyon** [MrAminiNezhad/tcp_optimizer_hybla#2]
Currently the test script has no improvement in QOS limiting speed. Hope to increase its active network competition. In the following test example, the network speed to China is very poor.

 Kernel             : 6.5.9-x64v2-xanmod1
 TCP CC             : hybla
 Virtualization     : KVM
 IPv4/IPv6          : ✓ Online / ✓ Online
 Organization       : 
 Location           : Fremont / US
 Region             : California
----------------------------------------------------------------------
 I/O Speed(1st run) : 269 MB/s
 I/O Speed(2nd run) : 316 MB/s
 I/O Speed(3rd run) : 342 MB/s
 I/O Speed(average) : 309.0 MB/s
----------------------------------------------------------------------
 Node Name        Upload Speed      Download Speed      Latency
 Speedtest.net    22.44 Mbps        609.25 Mbps         40.05 ms
 Los Angeles, US  882.53 Mbps       770.00 Mbps         10.64 ms
 Dallas, US       686.92 Mbps       584.78 Mbps         38.98 ms
 Montreal, CA     708.16 Mbps       805.70 Mbps         67.13 ms
 Paris, FR        331.18 Mbps       483.00 Mbps         133.66 ms
 Amsterdam, NL    533.03 Mbps       565.62 Mbps         137.94 ms
 Shanghai, CN     2.66 Mbps         356.45 Mbps         235.88 ms
 Chongqing, CN    0.43 Mbps         0.26 Mbps           215.48 ms
 Hongkong, CN     5.00 Mbps         5.25 Mbps           185.67 ms
 Mumbai, IN       282.03 Mbps       313.56 Mbps         256.07 ms
 Singapore, SG    323.05 Mbps       519.02 Mbps         210.85 ms
 Tokyo, JP        395.64 Mbps       501.81 Mbps         108.03 ms
----------------------------------------------------------------------
 Finished in        : 6 min 51 sec
 Timestamp          : 2023-11-01 22:22:49 CST
----------------------------------------------------------------------

**Comment by MrAminiNezhad** [comment]
Hello, dear friend, the script does not optimize external connections (speedtest), the script optimizes internal TCP and UDP requests (user to server connection)

**Comment by MrAminiNezhad** [comment]
> What are the differences and advantages with bbr3? i will try use wiregaurd openvpn hysteria for test this, right?

According to BBRV3 review, it works a bit better in terms of upload speed, but its ping is not suitable and it is 2 times more!

**Comment by MrAminiNezhad** [comment]
> Could you offer this for freebsd14, i want to use this for pfsense and opnsense router and with vpn.

I did not work with this version, but I will check if possible and provide a version.

**Comment by MrAminiNezhad** [comment]
> i have try the https://hysteria.network/zh/docs/advanced/Full-Server-Config/#_6    Brutal , Its network speed is obviously much faster than BBR3, and it performs particularly well on high-latency congested networks, but the disadvantage is that it can only use their own software. I hope to learn from their advantages of maximizing network preemption of network bandwidth so that our hybla can also have network competition.

A new version will be released soon and it is going to be much faster and stronger!

**Comment by Onair-santa** [comment]
May be Xanmod+Cake+BBR   - for my server it is the best combination/

**Comment by MrAminiNezhad** [comment]
Yes, different results have been presented compared to the network and software

**Comment by Onair-santa** [comment]
Can you advise me on the settings? It will be right for cake+bbr?
net.core.default_qdisc = cake
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_ecn = 2
net.ipv4.tcp_frto = 2
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_wmem = 4096 16384 4194304
net.ipv4.tcp_rmem = 4096 87380 4194304
net.ipv4.tcp_delack_min = 5
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_reordering = 3
net.ipv4.tcp_early_retrans = 3
net.ipv4.tcp_ssthresh = 32768
net.ipv4.tcp_frto_response = 2
net.ipv4.tcp_abort_on_overflow = 1
net.core.netdev_max_backlog = 250000
net.core.rmem_default = 4194304
net.core.wmem_default = 4194304
net.core.rmem_max = 4194304
net.core.wmem_max = 4194304
net.ipv4.tcp_max_tw_buckets = 5000

**Comment by MrAminiNezhad** [comment]
> Can you advise me on the settings? It will be right for cake+bbr?
> I'm not very knowledgeable about TCP settings. Then I’ll add your option to my script and the option with cake
> net.core.default_qdisc = cake
> net.ipv4.tcp_congestion_control = bbr
> net.ipv4.tcp_ecn = 2
> net.ipv4.tcp_frto = 2
> net.ipv4.tcp_low_latency = 1
> net.ipv4.tcp_mtu_probing = 1
> net.ipv4.tcp_no_metrics_save = 1
> net.ipv4.tcp_window_scaling = 1
> net.ipv4.tcp_sack = 1
> net.ipv4.tcp_timestamps = 1
> net.ipv4.tcp_wmem = 4096 16384 4194304
> net.ipv4.tcp_rmem = 4096 87380 4194304
> net.ipv4.tcp_delack_min = 5
> net.ipv4.tcp_fastopen = 3
> net.ipv4.tcp_syncookies = 1
> net.ipv4.tcp_reordering = 3
> net.ipv4.tcp_early_retrans = 3
> net.ipv4.tcp_ssthresh = 32768
> net.ipv4.tcp_frto_response = 2
> net.ipv4.tcp_abort_on_overflow = 1
> net.core.netdev_max_backlog = 250000
> net.core.rmem_default = 4194304
> net.core.wmem_default = 4194304
> net.core.rmem_max = 4194304
> net.core.wmem_max = 4194304
> net.ipv4.tcp_max_tw_buckets = 5000

I'm not sure you should check.
