### ISSUE TITLE
اعلام وضعیت 

### ISSUE THREAD

**Issue by Shellgate** [MrAminiNezhad/tcp_optimizer_hybla#3]
سلام و عرض ادب

تشکر می‌کنم از سازنده و توسعه دهندگان این اسکریپت
در اپدیت جدید مشکلات نصب قبلی حل گردید
به شخصه باعث بهبود عملکرد سرور ها شده ولی 
خود hybla باعث کندی سرعت میشود به همین منظور از 
من به شخصه بعد از نصب این اسکریپت تغییر به bbr و pcc
رو بهتر میدونم و علکرد بهتری دریافت کردم

یک پیشنهاد داشتم ساخت منوی برای دسترسی آسان که توان آپدیت داشته و از طریق کنسول بتوان اجرا کرد و همچنین قرار دادن bbr و pcc و سایرین در همین اسکریپت رو پیشنهاد میکنم

مرسی و تشکر

**Comment by MrAminiNezhad** [comment]
hybla باعث کندی نمیشه فقط گاهی درصورت نیاز سرعت رو کمتر میکنه چون به صورت هوشمند عمل میکنه سعی هاییلا اینه لهترین سرعت رو به یوزر ارائه بده
