### ISSUE TITLE
نصب رو هر پنل v؟

### ISSUE THREAD

**Issue by Amirnikoo66** [MrAminiNezhad/tcp_optimizer_hybla#4]
رو هر پنلی میشه نصبش کرد ؟ تداخل نداره ؟
و اینکه سیستم عامل سرور هم مهمه برای نصب ؟

**Comment by MrAminiNezhad** [comment]
سلام 

نوع پنل مهم نیستش و اصلا این بهینه ساز پنل نیست بهینه ساز سرور هست 

برای ابونتو 20 و 22 و سنت او اس 6 و 7 قرار گرفته
