### ISSUE TITLE
از کار افتادن اینترنت سرور

### ISSUE THREAD

**Issue by amirhossein1214** [MrAminiNezhad/tcp_optimizer_hybla#7]
سلام 
من اسکریپت شما رو نصب کردم دیگه سرورم بالا نیومد فقط الان میتونم از طریق vnc که سایت در اختیارم گذاشته سرورم رو ببینم در واقع نتورک سرورم دچار اشکال شده و پشتیبانی میگه باید او اس عوض کنی و من هم فایل x-ui  روی سروره و کل اطلاعاتمه چیکار کنم؟

**Comment by MrAminiNezhad** [comment]
> سلام 
> من اسکریپت شما رو نصب کردم دیگه سرورم بالا نیومد فقط الان میتونم از طریق vnc که سایت در اختیارم گذاشته سرورم رو ببینم در واقع نتورک سرورم دچار اشکال شده و پشتیبانی میگه باید او اس عوض کنی و من هم فایل x-ui  روی سروره و کل اطلاعاتمه چیکار کنم؟

گاهی وقت ها پیش میاد که سرور در زمان اپدیت مشکل برخورد میکند و این اتفاق میفته برای این مورد باید اون بخش از ایرادی که ایجاد شده را  شناسایی و رفع کرد اما شاید نصب مجدد بتونه براتون مشکل را حل بکنه

**Comment by amirhossein1214** [comment]
مهندس لطفا کمکم کن چون من یه عالمه یوزر دارم روی اون سرور و بک آپ هم ندارمم ازشون و تنها دسترسیم اینه که میتونم روی سرور کد بزنم لطفا راهنماییم کن

**Comment by MrAminiNezhad** [comment]
برای دسترسی به فایل دیتابیس از درون سرور به ادرس زیر برید : 

/etc/x-ui/

در این جا فایل x-ui.db را میتوانید ببینید

**Comment by amirhossein1214** [comment]
بله مهندس میتونم ببینم اما نمیتونم کپی کنم یا انتقالش بدم

**Comment by MrAminiNezhad** [comment]
از scp استفاده بکنید و به سرور دیگه انتقال بدید 

scp user@192.168.1.100:/home/user/file.zip /root/test

**Comment by amirhossein1214** [comment]
مهندس این ایمیل من هستش لطف کنید یه ایمیل بدید من لینک رو خدمتتون بفرستم amirhosseinamiri1215@gmail.com
